#ifndef CERTIFICATE_GENERATED_H_
#define CERTIFICATE_GENERATED_H_

namespace certificate {
    typedef enum { CT_ECC=0, CT_RSA=1 } CertType;

    const CertType serverCertType = CT_ECC;

    constexpr const char dname[] = "wicheck";

    const char serverKey[] PROGMEM = R"EOT(
-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIAcaBeGYPOi2/IptwRdoJImzpVOcR92VdIn9cDiJ44usoAoGCCqGSM49
AwEHoUQDQgAE8yKg7kU6bzfSkJ8rf73appmgLgbqkrK+SN7x54I2cCXFIpt2up/T
XCMBRIJbzCs2sqHCjFGXZCbdSHxVYGKLvA==
-----END EC PRIVATE KEY-----
)EOT";

    const char serverCert[] PROGMEM = R"EOT(
-----BEGIN CERTIFICATE-----
MIICHjCCAcUCFCoqhIUEDc2Fsjp9yhLBZzGW0+clMAoGCCqGSM49BAMCMIGRMQsw
CQYDVQQGEwJGUjEMMAoGA1UECAwDQlpIMRAwDgYDVQQHDAdSb3Njb2ZmMQwwCgYD
VQQKDAMxZTExDTALBgNVBAsMBEBsYW4xFjAUBgNVBAMMDXdpY2hlY2subG9jYWwx
LTArBgkqhkiG9w0BCQEWHjIuNzE4MjgxODNFMCt3aWNoZWNrQGdtYWlsLmNvbTAe
Fw0yMzA4MDUxMDQwMDBaFw00ODA3MjkxMDQwMDBaMIGRMQswCQYDVQQGEwJGUjEM
MAoGA1UECAwDQlpIMRAwDgYDVQQHDAdSb3Njb2ZmMQwwCgYDVQQKDAMxZTExDTAL
BgNVBAsMBEBsYW4xFjAUBgNVBAMMDXdpY2hlY2subG9jYWwxLTArBgkqhkiG9w0B
CQEWHjIuNzE4MjgxODNFMCt3aWNoZWNrQGdtYWlsLmNvbTBZMBMGByqGSM49AgEG
CCqGSM49AwEHA0IABPMioO5FOm830pCfK3+92qaZoC4G6pKyvkje8eeCNnAlxSKb
drqf01wjAUSCW8wrNrKhwoxRl2Qm3Uh8VWBii7wwCgYIKoZIzj0EAwIDRwAwRAIg
XT1sdtlAxLA+HdUKDAuHh7hvVpBZAENKjj8kFAsroO0CID9YPZQ+sw8GO3vPid5o
dBJ1HZBLIT1gt1vi6Wp6PKEk
-----END CERTIFICATE-----
)EOT";
}

#endif // CERTIFICATE_GENERATED_H_
