#ifndef _certificate_H_
#define _certificate_H_

namespace certificate {
    typedef enum { CT_ECC=0, CT_RSA=1 } CertType;

    const char dname[] = "wicheck";

    const CertType serverCertType = CT_ECC;

    const char serverKey[] PROGMEM = R"EOT(
-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIKOPJGl3bMVDWhxCcC7bLKwzUfmE+XfRwYicUC9RK25LoAoGCCqGSM49
AwEHoUQDQgAED3uZlUWv/PlQINkMPgcQ0UJvDn4SB9YO4CXS3bhvHS/GEiSeriEU
E7X7GPG3hkHbvykdNMO1Zsb/vyHanSc1Wg==
-----END EC PRIVATE KEY-----
)EOT";

    const char serverCert[] PROGMEM = R"EOT(
-----BEGIN CERTIFICATE-----
MIICpjCCAkygAwIBAgIUBINItlRuTn7I6LFFIp2fawRPSukwCgYIKoZIzj0EAwIw
gZAxCzAJBgNVBAYTAkZSMQwwCgYDVQQIDANCWkgxEDAOBgNVBAcMB1Jvc2NvZmYx
DDAKBgNVBAoMAzFlMTENMAsGA1UECwwEQGxhbjEWMBQGA1UEAwwNd2ljaGVjay5s
b2NhbDEsMCoGCSqGSIb3DQEJARYdMi43MTgyODE4M0UwK3dpc2NhbkBnbWFpbC5j
b20wHhcNMjAxMTEzMTkzMDQ2WhcNNDUxMTA3MTkzMDQ2WjCBkDELMAkGA1UEBhMC
RlIxDDAKBgNVBAgMA0JaSDEQMA4GA1UEBwwHUm9zY29mZjEMMAoGA1UECgwDMWUx
MQ0wCwYDVQQLDARAbGFuMRYwFAYDVQQDDA13aWNoZWNrLmxvY2FsMSwwKgYJKoZI
hvcNAQkBFh0yLjcxODI4MTgzRTArd2lzY2FuQGdtYWlsLmNvbTBZMBMGByqGSM49
AgEGCCqGSM49AwEHA0IABA97mZVFr/z5UCDZDD4HENFCbw5+EgfWDuAl0t24bx0v
xhIknq4hFBO1+xjxt4ZB278pHTTDtWbG/78h2p0nNVqjgYEwfzAdBgNVHQ4EFgQU
mGjGrIFaqY3amT3wfAWZb2OLp70wHwYDVR0jBBgwFoAUmGjGrIFaqY3amT3wfAWZ
b2OLp70wDwYDVR0TAQH/BAUwAwEB/zAsBgNVHREEJTAjgg13aWNoZWNrLmxvY2Fs
ggx3aXNjYW4ubG9jYWyHBMCoBAEwCgYIKoZIzj0EAwIDSAAwRQIhAKGT/QaHLuGg
G2yEFPTxZpcjzf4pbeX6Vm/BnEOkapINAiA3nh8aRy0UGLKZwwRUYOBsYEGLYkHo
OkkzIlcAffkg8A==
-----END CERTIFICATE-----
)EOT";
}

#endif // _certificate_H_
