#ifndef _certificate_H_
#define _certificate_H_

namespace certificate {
    typedef enum { CT_ECC=0, CT_RSA=1 } CertType;

    const char dname[] = "wicheck";

    const CertType serverCertType = CT_ECC;

    const char serverKey[] PROGMEM = R"EOT(
-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIEbOOpjbqKwYNAZMfNmVIembbUc2ig2VUrb8ccSxkrdaoAoGCCqGSM49
AwEHoUQDQgAEA2aEVUA/tx7u9e7faPLUoSGNYRqE7h6GTRFtlVIqMJ9por4lYi63
e8QcKzn1mUmOF3d2Cr4D0tI96lzbfVMa7g==
-----END EC PRIVATE KEY-----
)EOT";

    const char serverCert[] PROGMEM = R"EOT(
-----BEGIN CERTIFICATE-----
MIICpzCCAkygAwIBAgIUe3wM+nuuybMkYQMtdD5rYlOXy7MwCgYIKoZIzj0EAwIw
gZAxCzAJBgNVBAYTAkZSMQwwCgYDVQQIDANCWkgxEDAOBgNVBAcMB1Jvc2NvZmYx
DDAKBgNVBAoMAzFlMTENMAsGA1UECwwEQGxhbjEWMBQGA1UEAwwNd2ljaGVjay5s
b2NhbDEsMCoGCSqGSIb3DQEJARYdMi43MTgyODE4M0UwK3dpc2NhbkBnbWFpbC5j
b20wHhcNMjAxMTE0MDkzMTUwWhcNNDUxMTA4MDkzMTUwWjCBkDELMAkGA1UEBhMC
RlIxDDAKBgNVBAgMA0JaSDEQMA4GA1UEBwwHUm9zY29mZjEMMAoGA1UECgwDMWUx
MQ0wCwYDVQQLDARAbGFuMRYwFAYDVQQDDA13aWNoZWNrLmxvY2FsMSwwKgYJKoZI
hvcNAQkBFh0yLjcxODI4MTgzRTArd2lzY2FuQGdtYWlsLmNvbTBZMBMGByqGSM49
AgEGCCqGSM49AwEHA0IABANmhFVAP7ce7vXu32jy1KEhjWEahO4ehk0RbZVSKjCf
aaK+JWIut3vEHCs59ZlJjhd3dgq+A9LSPepc231TGu6jgYEwfzAdBgNVHQ4EFgQU
0tC0akXCa3EZeSRblVvREI6y5rMwHwYDVR0jBBgwFoAU0tC0akXCa3EZeSRblVvR
EI6y5rMwDwYDVR0TAQH/BAUwAwEB/zAsBgNVHREEJTAjgg13aWNoZWNrLmxvY2Fs
ggx3aXNjYW4ubG9jYWyHBMCoBAEwCgYIKoZIzj0EAwIDSQAwRgIhAJchP7ZnqdsR
/TQjDgsSgiokbcuXuCGl2vsyzYTxMw0dAiEA5GJF9vj2ruIptij2K0gphtMvpRBt
gFAmmTSvkyMGpr4=
-----END CERTIFICATE-----
)EOT";
}

#endif // _certificate_H_
